language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - sudo apt-get update
  - wget https://github.com/ringing-lib/ringing-lib-deb/releases/download/v0.4.0-4/libringing-dev_0.4.0-4_amd64.deb
  - wget https://github.com/ringing-lib/ringing-lib-deb/releases/download/v0.4.0-4/libringing-bin_0.4.0-4_amd64.deb

install:
  - sudo apt-get install libreadline6 libgdome2-0
  - sudo dpkg --install libringing-dev_0.4.0-4_amd64.deb
  - sudo dpkg --install libringing-bin_0.4.0-4_amd64.deb
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - flake8 method_lines
  - ./method-lines.py all examples/*/*
